### ISSUE TITLE
How to increase number of home sets

### ISSUE THREAD

**Issue by TheWyzer** [Speedy2025/speedys-essentials#3]
As the title suggests, I would like to increase the number of home sets from 10 to a higher value.

I play SP, and really appreciate this datapack, as adding MODs to Modpacks tends to cause so many issues, not to mention updates are fully manual and can cause catastrophic breaks.  I am playing on an older version Modpack, 1.18.2, which is why this request is occurring now.

**Comment by Speedy2025** [comment]
Greetings! It's been over two years since I did anything Minecraft related, so my apologies if I'm a little bit off.

The simple way to do this is to navigate in the datapack to the following file:

`data/se/functions/home/misc/max_homes.mcfunction`

Inside, you'll notice a bunch of stuff. Simply replace all of it with the following:

`scoreboard players set #se.homes.max se.storage <#>`

Of course, you'll need to replace <#> with the appropriate number of homes you'd like. Just keep in mind that a high number of homes increases the likelihood that PlayerDB will start having issues, especially if you have a lot (10+) of players. Since it is just you, it shouldn't cause any issues other than a small lag spike to increase it to something quite higher.

I hope this helps!
-5202

P.S. Don't be confused by the other max_homes function. That one was just so that my old server wouldn't complain as I made the datapack primarily for it. Also, the number of homes you can have goes up over time unless you override it using the steps above.

**Comment by TheWyzer** [comment]
Thank you for the response.  I had notice that there hadn't been anything done on this project in some time, and I was simply hopeful.  I really appreciate the help, and it appears to be working fine.

As  a note I did try to use "hubs" before creating the issue, however at least via the Hub Management Menu, when trying to set hubs it appears to assign them to -X (I.e. clicking [Set hub] results in "Triggered [Hub] (set value to -2)", making it  unusable as it assigns a -.

Again thanks for your help, it is much appreciated.

**Comment by Speedy2025** [comment]
Not a problem!

As for setting a hub: generally negative values indicate operations with the exception of tpr/tprh. It should work as expected as -2 was the set hub operation. If it doesn't, please open a new issue and I'll try to get my setup built again to debug it.

Each user can only create one hub which is assigned to their id. This is hard-coded unfortunately to keep things simple for everyone. Since you're in singleplayer, it should just be one. To return to it, just use `/trigger hub set 1`.
