### ISSUE TITLE
Unable to set additional hubs

### ISSUE THREAD

**Issue by TheWyzer** [Speedy2025/speedys-essentials#4]
When I use the Hub Management Menu, when trying to set a hub it appears to assign them to -2 (I.e. clicking [Set hub] results in "Triggered [Hub] (set value to -2)".  

The actual result in this case after making changes from Issue #3: Adding additional Home sets, now results in [Set hub] actually setting Hub 1, even though the output states _set to value -2_ .  As previously, per my recollection, using `/trigger hub set 1` took me to location 0,0,0.

Is there something I am missing on how to set additional hubs?  I have tried `/trigger hub add 2` it does not create an additional hub, and results in error `[Hubs] Hub 2 does not exist`.

Info:
I am playing on Single Player (Minecraft 1.18.2)
Using Forge 40.2.4
Modpack DeceasedCraft 5.5.5.
Added 1 mod "Borderless Window" which allows full screen always active view.

**Comment by Speedy2025** [comment]
Greetings.

The first part is intended behavior. As previously mentioned, operations are assigned to a negative value. Any time you do something regarding your hub, such as setting a hub or disabling others from using it, it'll be negative. The previous issue increased the number of homes, but did not increase the number of hubs. This is because you can only have **one hub per player**. Your hub should be 1. `/trigger hub set 1`

Other than the fact that homes are personal and flexible and hubs are public and rigid in design, there is no functional difference. Generally, you should use homes for most things and keep your hub for your base of operations.

Now, onto the question I have: Are you being teleported to 0,0,0 after setting your hub?

If you could, please send a screenshot of the hub management menu. I'm primarily looking for what it says your hub is. `/trigger hub set -1`

**Comment by TheWyzer** [comment]
OK, understood, just thought there were ways to have additional hubs. 

> Now, onto the question I have: Are you being teleported to 0,0,0 after setting your hub?

That was the result of using the `/trigger hub set 1` and there was no change to the hub location after trying to change it via the Hub Management Menu.   Since the changes to the number of homes per issue #3, hub 1 now works when set via the statement I made earlier.  It could  simply be that I run on Linux and on rare occasions it has issues, more so if file names are involved.

I appreciate your support and responses.
